ORG 1000H
TABLA DB DUP(2,4,6,8,10,12,14,16,18,20)
FIN DB ?
TOTAL DB ?
MAX DB 13

ORG 2000H
MOV AL, 0
MOV CL, OFFSET FIN-OFFSET TABLA
MOV BX, OFFSET TABLA
MOV DH, MAX
MOV DL, 0

SUMA: ADD AL, [BX]
CMP DH, [BX]
JS NO_CUENTO
INC DL
NO_CUENTO: INC BX
DEC CL
JNZ SUMA
MOV TOTAL, AL               ;Modificacion para que el resultado sea almacenado en memoria
HLT
END